---
title: "Intro to MCMC: Assignment"
output:
  html_document: default
language: R
---

<!-- To render the assignment in Rmarkdown, enter the command below in the R console -->
<!-- rmarkdown::render("Class_22_Assignment.Rmd") -->

#### Due by 11:59 on 11/15

Save this Rmarkdown script as a file named “YourlastName_Assignment21.Rmd”. 
For each question, fill out the answer and, where requested, 
provide the relevant R code using "```" and the echo = TRUE argument.

When finished, Knit your script together into an html report, 
saved as “YourlastName_Assignment21.html” and upload the 
resulting file to the D2L site (in today’s class folder) to turn it in. 
It is due before our next class.

\

**This homework assignment will test your abilities to:**

1. think critically and creatively about Bayesian inference

2. extrapolate from in-class exercises to apply Bayesian inference to arbitrary distributions

3. use your R skillz: function building, data visualization, etc.

\


### Question 1

1. Explain, in your own words, the goal and steps of an MCMC algorithm.


### Question 2

Below is a chunk of R code that implements an MCMC algorithm 
to estimate the rate parameter ($\lambda$) of a Poisson distribution. 
This code is uncommented - please write a comment for each line 
explaining what that line is doing. It may help to load in poisData.Robj from d2l and work through the code line by line to see what it's doing.

```{r}

load('poisData.Robj')

calcPostProb <- function(poisData,lambda){
	lnL <- sum(dpois(x=poisData,lambda=lambda,log=TRUE))
	lnPrior <- dnorm(x=lambda,mean=1,sd=1e6,log=TRUE)
	return(lnL + lnPrior)
}

mcmcPoisson <- function(poisData, n.iter){
	lambdaSamples <- rep(NA,n.iter)
	postProbSamples <- rep(NA,n.iter)
	lambda <- abs(rnorm(1))
	postProb <- calcPostProb(poisData,lambda)
	lambdaSamples[1] <- lambda
	postProbSamples[1] <- postProb
	for(i in 1:n.iter){
		lambdaPrime <- lambda + rnorm(n=1,mean=0,sd=0.3)
		if(lambdaPrime > 0){
			postProbPrime <- calcPostProb(poisData,lambdaPrime)
			postRatio <- exp(postProbPrime - postProb)
			if(postRatio > runif(n=1,min=0,max=1)){
				lambda <- lambdaPrime
				postProb <- postProbPrime
			}
		}
		lambdaSamples[i] <- lambda
		postProbSamples[i] <- postProb
	}
	return(
		list(
			"lambdaSamples" = lambdaSamples,
			"postProbSamples" = postProbSamples)
	)
}
```


### Question 3

Use the code above to do inference on the rate parameter (lambda)
I used to simulate the Poisson-distributed data saved in the 
.Robj file in the Class 21 homework folder on D2L. Note that the object that
will be loaded from the poisData.robj file is called poisData.

Provide some visualizations of the results of your MCMC run.
Use your imagination here - if you were a data scientist, 
what plots would you want to show your client to convince 
them you had done a good job?