---
title: "Model building: deterministic functions"
output:
  html_document: default
  pdf_document: default
language: R
---

<!-- To render the assignment in Rmarkdown, enter the command below in the R console -->
<!-- rmarkdown::render("Class_23_Assignment.Rmd") -->

#### Due by 11:59pm on Nov 20

Save this Rmarkdown script as a file named “YourlastName_Assignment22.Rmd”. 
For each question, fill out the answer and, where requested, 
provide the relevant R code using "```" and the echo = TRUE argument.

When finished, Knit your script together into an html report, 
saved as “YourlastName_Assignment22.html” and upload the 
resulting file to the D2L site (in today’s class folder) to turn it in. 
It is due before our next class.

\

**This homework assignment will test your abilities to:**

1. think critically and creatively about model building

2. extrapolate from in-class exercises to simulate data and do inference with a linear model

3. extrapolate from previous lecture materials to apply Bayes' Theorem to inference with a linear model

4. hone your R skillz: function building, data visualization, etc.

\

### Question 1

Explain in your own words what each of the terms in the equation below is, 
as well as what the equation as a whole is describing.

$Y_i \sim \mathcal{N}(\mu_i=f(x_i),\sigma)$



### Question 2

1. 
Here is a function you can use to simulate data based on a linear model
with Gaussian-distributed error.
```{r}
myLinearSim <- function(i){
  myMean = myIntercept + i*myBeta ## get the mean based on a linear equation
  responseI = rnorm(n=length(i), myMean, sd=mySigma) ## add in the normally distributed error to get a response
  return(responseI)
}
```

Simulate a dataset of 1000 datapoints using a linear model and
Gaussian-distributed error with the following parameter values:

	- intercept = 12
	- sigma = 10
	- predictor effect size = -1.3

You may generate values of the predictor variable however you wish.


### Question 3

Use the function lm() to infer the parameter values used 
to simulate these data.  Confirm your results by comparing the
estimates from your model with the parameters you used
to simulate the data.


### Question 4

Calculate the numerator of Bayes' Theorem 
for the dataset you simulated in Question 1 
assuming the following:

* intercept ($\alpha$) = 13
* effect size ($\beta$) = -1
* standard deviation ($\sigma$) = 11
* $\alpha \sim \mathcal{N}(0,1)$
* $\beta \sim \mathcal{N}(0,1)$
* $\sigma \sim \text{Exp}(1)$

[hint: don't forget about the log product rule]