---
title: "Intro to Bayes: Assignment"
output:
  html_document: default
language: R
---

<!-- To render the assignment in Rmarkdown, enter the command below in the R console -->
<!-- rmarkdown::render("Class_20_Assignment.Rmd") -->

#### Due by 11:59pm on 11/13

Save this Rmarkdown script as a file named “YourlastName_Assignment20.Rmd”. 
For each question, fill out the answer and, where requested, 
provide the relevant R code using "```" and the echo = TRUE argument.

When finished, Knit your script together into an html report, 
saved as “YourlastName_Assignment20.html” and upload the 
resulting file to the D2L site (in today’s class folder) to turn it in. 
It is due before our next class.

\

**This homework assignment will test your abilities to:**

1. think critically and creatively about Bayesian statistics

2. extrapolate from in-class exercises to apply Bayesian inference to arbitrary distributions

3. use your R skillz: function building, data visualization, etc.

\


### Question 1

RSV (respiratory syncytial virus) is
a flu-like illness that infects virtually all children in their 
first few years of life. 

To detect RSV, healthcare providers generally administer antigen tests, 
which are cheaper and faster (although generally less accurate) than PCR-based tests.
The most commonly used RSV antigen test has a 91.7% sensitivity and a 98.9% specificity. 
A child shows some symptoms of RSV, so we get him
an antigen test, which comes back positive. 
Given that result, what is the probability the child is actually infected with RSV?

In your calculations, assume the following:\

-The child can be treated as a random draw from the <2yos of Ingham County\
-The probability that any child under two years old in Ingham County has RSV is 0.015.



### Question 3

3a) Building on the results from Question 2, 
write an R function that explores how the probability the child is actually infected with RSV 
given a positive result from an antigen test 
is dependent on the number of infected toddlers in Ingham County.
The function should take as its arguments: \
 -the percentage of toddlers in Ingham County who are actively infected \
 -the sensitivity of the antigen test (from Question 2)\
 -the specificity of the antigen test (from Question 2)\
 
and it should return the probability a given toddler is infected with RSV given the positive test result.




3b) At what background level of RSV prevalence in Ingham County does 
the probability of a given toddler actually being infected given a positive antigen test result go above 0.9?

