---
title: "Binomial distribution"
author: "Gideon Bradburd"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  ioslides_presentation:
    transition: 0.001
    bigger: true
    runtime: shiny
---
<!-- to run this shiny demo of the binomial distribution -->
<!-- enter the following command into R's console:		 -->
<!-- rmarkdown::run("binomial_shiny_demo.Rmd") 	 		 -->
<!-- 											 		 -->
<!-- more info at and lots of tutorials/resources 		 -->
<!-- at http://shiny.rstudio.com/articles/#first-app	 -->


***

## Brief history {.build}

 - First derived by James (aka Jacques?!) Bernoulli in 1713.
 
 - Fun fact
	+ James wanted the words "Although changed, I rise again the same" inscribed on his tombstone
 
## Notation, parameters, bounds

If a random variable $X$ is binomially distributed, we write 

<div class="centered">
$\Large X \sim B(n,p)$
</div>

\

 - $n$ is the number of trials (e.g., the number of times you flip a coin)

 - $p$ is the probability of success in each trial (e.g., the probability of flipping a heads)

 - the binomial distribution is a **discrete** probability distribution
 
 - a draw from a binomial distribution is bounded between 0 and $n$
 
## Mean

The mean of a binomial is given by 

<div class="centered">
$\Large \mathbb{E}[X] = np$
</div> 

\

### Intuition:
A larger number of trials will increase the overall expected number of successes (more flips = more heads).

A higher probability of success ($p$) will increase the expected number of successes (higher chance of heads = more heads).

When there are no trials ($n$ = 0), or when the probability of a success is 0 ($p$ = 0), 
the mean is also 0.

## Variance
The variance is given by

<div class="centered">
$\Large \mathbb{V}ar(X) = np(1-p)$
</div>

\

### Intuition:
A larger number of trials increases the variance (more possible outcomes)

Extreme values of $p$ give lower variances because outcomes start to get 
squished up against the hard bounds of the distribution.

When $p$ is 0 or 1, there is no variance, because all outcomes are failures or successes, respectively.

## Things that are binomially distributed

 - coin flips
 
 - allele frequencies
 
 - public opinion (from polls)
 
 - wins/losses (e.g., for a team)

##
```{r, echo=FALSE}
library(shiny)
  # input and output definitions
  # this is where you define the parameters of the distribution
  # (the binomial distribution has 2 parameters, `n' and `p',
  #		plus I have to define the number of replicates)
inputPanel(
 # Input: probability of success
 sliderInput("p", "probability of success (p):",
             min = 0, max = 1,
             value = 0.5),
 ## Input: sample size
 sliderInput("n", "number of observations (n):",
             min = 1, max = 5000,
             value = 100, step = 10),
 ## Input: number of replicates
 sliderInput("n.reps", "number of replicates (trials):",
             min = 1, max = 5000,
             value = 100, step = 10)
)

# this function determines how the output 
# of the sliders is plotted
renderPlot({
  	# simulate data from the appropriately parameterized distribution
    x <- rbinom(n = input$n.reps,size = input$n,prob = input$p)
	# dynamically define a plot title that gives summaries of the data
	plot.title <- sprintf("Histogram of binomial draws\nmean=%s ; np=%s",
							round(mean(x),1),
							input$n*input$p)
  	# visualize simulated data as a histogram
    hist(x, col="darkblue", border = "white",
         xlab = "Number of successes",
         xlim=c(0,input$n),
         main = plot.title,
         breaks=min(length(x),15))
})
```