---
title: "checking-data.Rmd"
output: html_document
date: "2022-12-01"
---

Group silence of the lambdas 
##
```{r, echo=T}
library(bbmle)
setwd("~/Documents/ibio830/battles/")

myData = read.csv('silence-of-the-lambdaslinear_data.csv')


a <- -1
b <- -.41 

invLink <- function(z){
	return(-z^-1)
}

  
detFunc <- function(x,a,b){
	return(a*(x^b))
}




mod <- mle2(response ~ dexp(rate=invLink(detFunc(predictor,a,b))),
             data=myData,
             start=list("a"=-1, "b"=-.5)
             )

### this issue is the det function




##
mod <- mle2(response ~ dexp(rate=invLink( detFunc(predictor,a,b))),
            data=myData,
            start=list("a"=-1,"b"=-.41))

#modData <- invLink(mod@coef[1]*myData$predictor^mod@coef[2])
modData <- a*myData$predictor^b


plot(myData$predictor, detFunc(myData$predictor, a, b), col="red")
points(myData$predictor, myData$response)


```

Group R Bug
## emailed to fix it

```{r}
myData <- read.csv('rbug-data.csv')

N0 <- 6
decay <- 0.18
set.seed(123)
x <- rnorm(1000)

detFunc <- function(x,a,b){
	return(exp(-a*(x*-b)))
}

invLink <- function(z){
	return(exp(z))
}

response <- rpois(1000, lambda = invLink(N0 * exp(-decay*x)))
myData$response2<-response

mod <- mle2(response ~ dpois(lambda=invLink( detFunc(predictor,N0,decay))),
            data=myData,
            start=list("a"=0,"b"=0))

mod



mod2 <- mle2(response2 ~ dpois(lambda=invLink( detFunc(x,a,b))),
            data=myData,
            start=list("a"=6,"b"=0.1))

mod2


plot(myData$predictor, myData$response)
points(myData$predictor,modData, col='red')


```

Rbug take 2

```{r}
myData = read.csv('R bug Mystery Data 12022023.csv')

a <- 6
b <- 0.18

# Setting function for the expontential decay
detFunc <- function(x, a, b){
  a*exp(-b*x)
}

# Inverse function for the exponential decay
invLink <- function(p){
    x <- exp(p)
}

mod <- mle2(response ~ dpois(lambda=invLink( detFunc(predictor,a,b))),
            data=myData,
            start=list("a"=0,"b"=0))

mod
```

Team Hyrule


```{r}
myData <- read.csv('HyruleScenario-final.csv')

detFunc <- function(x,a,b){
  return(a*exp(-b*x))
}

# specify the inverse link function
invLink <- function(z){
  return(z)
}

a<-100000
b<-0.016
s=10

mod <- mle2(response ~ dnorm(mean=invLink( detFunc(predictor, a, b)), sd = s),
            data=myData,
            start=list("a"=a,"b"=b, s=10))

mod

```

Mice -- this one is good!

```{r}

myData=read.csv('mice_survive.csv')

invLink <- function(x){
  p <- 1/(1+exp(-x))
  return(p)
}

detFunc <- function(x,a,b){
	return(a+b*x)
}

a=0
b=1

## its an binom dist. But where's the deterministic function? Is it just linear and a is 0, b is 1?

mod <- mle2(Mice~ dbinom(size=20,prob=invLink( detFunc(temperature, a, b))),
            data=myData,
            start=list("a"=0,"b"=1))

mod


modData <- invLink( detFunc(myData$temperature, a, b))*20
plot(myData$temperature, myData$Mice)
points(myData$temperature, modData, col="darkred")

```

Statfish

```{r}
myData = read.csv('statfish-data.csv')

detFunc <- function(x, a, b){
  return(a * x^b)
  
}

a = 2
b = 0.25

invLink <- function(x){
 exp(x)
}


mod <- mle2(Response~ dpois(lambda=invLink( detFunc(Predictor, a, b))),
            data=myData,
            start=list("a"=2,"b"=0.25))
mod




```

Dodocode

There is an issue with how they generated their response variable, since they didn't specify n and the first entry of rexp is n.

```{r}
myData = read.csv('dodo.csv')

detFunc <- function(x,a,b){ #defining a linear deterministic function
  return(a + b*x)
}

a = 1e12
b = 1e13

invLink <- function(p){ #specifying inverse link function for an exponential distribution
  return(-p ** -1)
}

mod <- mle2(response~ dexp(rate=invLink( detFunc(predictor, a, b))),
            data=myData,
            start=list("a"=1e12,"b"=1e13))
mod




```

Dodocode take 2

```{r}
myData=read.csv('dododata.csv')

detFunc <- function(x,a,b){ #defining a linear deterministic function
  return(a + b*x)
}

a = 10
b = 10

invLink <- function(p){ #specifying inverse link function for an exponential distribution
  return(-p ** -1)
}

mod <- mle2(response~ dexp(rate=-invLink( detFunc(predictor, a, b))),
            data=myData,
            start=list("a"=10,"b"=10))
mod

```

dodo take 3

```{r}
myData <- read.csv('dodo_population.csv')

detFunc <- function(x,a,b){ #defining a linear deterministic function
  return(a + b*x)
}

invLink <- function(p){ #specifying inverse link function for an exponential distribution
  return(p ** -1)
}



mod <- mle2(response~ dexp(rate=invLink( detFunc(predictor, a, b))),
            data=myData,
            start=list("a"=1,"b"=1))
mod

```


Team Jerry/Emily/Charlie

```{r}

myData <- read.csv('Relationship between residual drug and time.csv')

detFunc <- function(x,a,b){ #defining a linear deterministic function
  return(a*exp(-b*x))
}

invLink <- function(z){ #specifying inverse link function for an exponential distribution
  return(z)
}


alpha<-100    # Initial venom concentration (N0)
beta<-0.1     # decay constant (lambda)
sd<-1.5       #sd of normal distribution


mod <- mle2(response~ dnorm(mean=invLink( detFunc(predictor, a, b)), sd),
            data=myData,
            start=list("a"=1,"b"=1, 'sd'=1))
mod



```

Grigsby group -- this is fine

```{r}
myData <- read.csv('frogs.csv')

detFunc <- function(x,a,b){ #defining a linear deterministic function
  return(a*x^b)
}

invLink <- function(z){ #specifying inverse link function for an exponential distribution
  return(exp(z))
}

alpha <- 4.5
beta <- -0.03


mod <- mle2(response~ dpois(lambda=invLink( detFunc(predictor, a, b))),
            data=myData,
            start=list("a"=4.5,"b"=-0.03))


mod

```


