---
title: "Simulation/Inference Battle Assignment!"
output:
  html_document:
    toc: true
---

<!-- To render the assignment in Rmarkdown, enter the command below in the R console -->
<!-- rmarkdown::render("SI_battle_assignment.Rmd") -->

```{r,echo=FALSE}
	#set any global options
	options(digits=3)
	set.seed(123)
```

## Simulation/Inference battles!!!

The goal of this assignment is to demonstrate the power of inference. 
Your team will simulate a secret dataset that will be handed off to another team, 
and their challenge will be to infer the parameters you used to simulate your data. 
Likewise, you will receive another team's dataset 
with the same goal of inferring the parameters of 
the model they used to simulate their dataset.
At the end, you will present your results to the class, 
and the group that does the best job inferring the parameters the 
opposing team used to simulate their data will win **_eternal glory_**.

### Organization

 - Students divide into groups
 	+ come up with an awesome, stats-inspired team name: 
 		+ e.g., "Poisson of a Preacher Man"

### Simulation

 - Each team picks a **probability distribution** from the following list:
 	  1. normal
 	  2. exponential
 	  3. binomial
 	  4. poisson

 - and a **deterministic function** from the following list:
 	  1. linear
 	  2. exponential decay
 	  3. logistic (use the formulation from the slides!)
 	  4. power-law
 
 - simulate 1000 data points (that's 1000 responses and 1000 associated predictors) with the probability function, deterministic function, and link function.

 - **Make an Rmarkdown document** for the instructors that contains 
 	1. the code used to simulate the data 
 	2. the written scenario 
 	3. a plot of the output
 	4. a demonstration that if you run mle2() with the correct distribution and deterministic function, you recover the simulated parameters.

 	
 - **hand data off to the other team** after Sophie or Emily has approved your data, send the following files to the team that will be inferring your data:
	  1. a **.csv file** containing 2 columns, labeled "predictor" and "response"
 	  2. a **realistic and well-motivated writeup** of a biological scenario 
 	explaining what the question is and what data were collected to answer it. This can be in a text file or Rmarkdown file.
    - Do not send them the code you used to generate the data (unless you really want them to win!!!)	
 	


### Inference

 - Once you have the data, infer the parameters of the model 
 used to simulate the data with a generalized linear model.
 
 - This means you'll have to make choices about what distribution, 
 deterministic function, and possibly link function to use
 
 - Do inference on all parameters of the model
 	+ at most 3 parameters:
 		+ 2 for the deterministic function
 		+ up to 1 other: e.g.,
 			+ $y_i \sim \mathcal{N}(\mu_i = \alpha + \beta x_i, \sigma)$
 		+ or
 			+ $y_i \sim \mathcal{N}(\mu, \sigma_i = \alpha + \beta x_i)$
 
### Presentation
 
 - Prepare a brief (<5 min) presentation:
 	+ plot of raw data (predictor v. response)
 	+ briefly explain modeling choices
 		+ what distribution, what deterministic function, what link function, why
 	+ present parameter estimates
 	+ show model fit on raw data
 - Presentation should be prepared as an Rmarkdown document and submitted to instructors
 
 - Other team will reveal true answer
 
### Timeline

 - Nov 21 - make groups, start to plan, work within groups to simulate data
 
 - Nov 25 (Monday) - by 9 am, email simulation scenario to Emily and Sophie to get the green light
 
 	+ teams with problems in their simulation code/scenario will have until Nov 26 at 5pm to get their simulations cleared by instructors

 - Dec 3 - data handoff between teams at the beginning of class. Teams use classtime to infer the data and make presentation.

 - Dec 5 - presentations!
 
 	+ **Presentations must be submitted to the D2L dropbox by by 9am on Dec 5 ** 