---
title: "checking-silence-of-the-lambdas"
output: html_document
date: "2023-12-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bbmle)
```

Trying with their data
```{r}

setwd("~/Documents/ibio830/battles/")

myData = read.csv('silence-of-the-lambdaslinear_data.csv')


a <- -1
b <- -.41 

invLink <- function(z){
	return(-z^-1)
}

detFunc <- function(x,a,b){
	return(a*(x^b))
}

mod <- mle2(response ~ dexp(rate=invLink( detFunc(predictor,a,b))),
            data=myData,
            start=list("a"=-1,"b"=-.41))


mod
```

Despite knowing the a and b parameters used in the distribution, it's impossible for mle2 to estimate those parameters.

Trying with a linear deterministic function instead:

```{r}

detFunc2 <- function(x,a,b){
  return(a+b*x)
}

myData$testResponse=rexp(1000, rate=invLink(detFunc2(myData$predictor,a,b)))

mod2 <- mle2(testResponse ~ dexp(rate=invLink(detFunc2(predictor,a,b))),
             data=myData,
             start=list("a"=-1, "b"=-0.41)
             )

mod2


```

