---
title: "Intro to Likelihood: Assignment"
output:
  html_document: default
language: R
---

<!-- To render the assignment in Rmarkdown, enter the command below in the R console -->
<!-- rmarkdown::render("Class_19_Assignment.Rmd") -->

#### Due by midnight before the beginning of next class (11/10)

Save this Rmarkdown script as a file named “YourlastName_Assignment19.Rmd”. 
For each question, fill out the answer and, where requested, 
provide the relevant R code using "```" and the echo = TRUE argument.

When finished, Knit your script together into an html report, 
saved as “YourlastName_Assignment19.html” and upload the 
resulting file to the D2L site (in today’s class folder) to turn it in. 
It is due before our next class.

\

**This homework assignment will test your abilities to:**

1. think critically and creatively about probability distributions

2. extrapolate from in-class exercises to apply likelihood-based inference to arbitrary distributions

3. use your R skillz: function building, data visualization, etc.

\

### Question 1

What is the log product rule, and how/why is it used for likelihood-based inference?
\
\
\

### Question 2

Everything from class used the binomial distribution, so let's try using the Poisson distribution instead.
\
\
\
a) If $X \sim \text{Pois}(\lambda)$, calculate $P(2 | \lambda=4)$
\

b) You make 2 draws from the Poisson distribution and get 2 the first time, and 3 the second time. What is the probability of this outcome of $\lambda$ is 4?
\
\
\

c) What is the log-likelihood of the outcome from part b?

\
\
\

### Question 3

Use maximum likelihood inference to estimate 
the parameter values I used to simulate data from a Poisson distribution, 
which are saved as a .Robj file in the Class 19 folder.
You should refer to the lecture .Rmd file for helpful reference 
code that you can cannibalize.
Your answers from Question 2 will also be helpful.

I've included pseudocode below to help you on your journey, but you don't need to use it if it makes more sense to you to go a different route.

```{r}
################
#	load in simulated dataset 
#	hint: see the function load()
#		don't forget to specify full file paths and use quotes
################

################
# visualize data
#	hint: hist() is always a friend
################


################
# get MLE:
################

# don't forget that the probability of a shared event 
#	should be calculated as the sum of the logs of the 
#	simple events that make up the shared event
#

## pick a set of lambdas based on the histogram

## write a function to calculate the log-likelihood of the data for a given lambda

# run your function on all the lambdas in your set


## plot your data to see if it looks right

# ML estimate for lambda is:


```