---
title: "Gamma distribution"
author: "Emily Josephs"
date: "Nov 3 2022"
output:
  ioslides_presentation:
    transition: 0.001
    bigger: true
    runtime: shiny
---
<!-- to run this shiny demo of the binomial distribution -->
<!-- enter the following command into R's console:		 -->
<!-- rmarkdown::run("binomial_shiny_demo.Rmd") 	 		 -->
<!-- 											 		 -->
<!-- more info at and lots of tutorials/resources 		 -->
<!-- at http://shiny.rstudio.com/articles/#first-app	 -->


***

## Brief history {.build}

 - Derived by Laplace? Or Euler? No one knows.
 
 - The distribution of waiting times for a certain number of things to happen
 
## Notation, parameters, bounds

If a random variable $X$ is gamma distributed, we write 

<div class="centered">
$\large X \sim \Gamma(\alpha,\beta)$
</div>

 - $\alpha$ is the shape parameter (ie how many events are you waiting for)

 - $\beta$ is the rate parameter (the average rate of things)
 
 - $\beta = \frac{1}{\theta}$ where $\theta$ is the scale parameter

 - the gamma distribution is a **continuous** probability distribution
 
 - a draw from a gamma distribution is bounded between 0 and infinity
 
## Mean

The mean of a binomial is given by 

<div class="centered">
$\Large \mathbb{E}[X] = \alpha\theta = \frac{\alpha^{2}}{\beta}$
</div> 

\

### Intuition:

Wait times will be longer if you are waiting for more things ($\alpha$) or the rate ($\beta$) is slower.

## Variance
The variance is given by

<div class="centered">
$\Large \mathbb{V}ar(X) = \alpha\theta^{2} = \frac{\alpha^{2}}{\beta^{2}}$
</div>

\

### Intuition:
The variance of wait times goes up if you're waiting for more things, or if the rate is slower.

## Things that are gamma distributed

 - the time it takes for a certain number of cell divisions to occur
 
 - the distribution of fitness effects of new mutations

##
```{r, echo=FALSE}
library(shiny)
  # input and output definitions
  # this is where you define the parameters of the distribution
  # (the binomial distribution has 2 parameters, `n' and `p',
  #		plus I have to define the number of replicates)
inputPanel(
 # Input: probability of success
 sliderInput("k", "shape:",
             min = 0, max = 20,
             value = 1, step=.25),
 ## Input: sample size
 sliderInput("theta", "scale:",
             min = 0, max = 20,
             value = 1, step = .25),
 ## Input: number of replicates
 sliderInput("n.reps", "number of replicates (trials):",
             min = 1, max = 5000,
             value = 100, step = 10)
)

# this function determines how the output 
# of the sliders is plotted
renderPlot({
  	# simulate data from the appropriately parameterized distribution
    x <- rgamma(n = input$n.reps,shape = input$k, scale = input$theta)
	# dynamically define a plot title that gives summaries of the data
	plot.title <- sprintf("Histogram of gamma draws")
  	# visualize simulated data as a histogram
    hist(x, col="mediumpurple3", border = "white",
         xlab = "",
         xlim=c(0,max(x)),
         main = plot.title,
         breaks=min(length(x),15))
})
```