---
title: "Probability Distributions: Assignment"
output:
  html_document: default
language: R
---

<!-- To render the assignment in Rmarkdown, enter the command below in the R console -->
<!-- rmarkdown::render("Class_18_Assignment.Rmd") -->

#### Due by the beginning of next class 

Save this Rmarkdown script as a file named “YourlastName_Assignment18.Rmd”. 
For each question, fill out the answer and, where requested, 
provide the relevant R code using "```" and the echo = TRUE argument.

When finished, Knit your script together into an html report, 
saved as “YourlastName_Assignment18.html” and upload the 
resulting file to the D2L site (in today’s class folder) to turn it in. 
It is due midnight before the next class.

\

Please spend some time working through the shiny demos that your classmates made (available on d2l) and answer the following questions:

### Question 1

Choose which probability distribution (from the bank below) would best describe 
the following types of data and briefly (one sentence) explain why.

bank: {beta, exponential, gamma, lognormal,
	   normal, uniform, poisson, geometric, 
	   negative binomial, binomial}
	   
**Many of these are subjective so it's OK if your answers differ from the key**	   
	   
1. Lengths of ribbon left over after wrapping presents

**exponential** - I think of where the ribbon gets cut as a poisson process, and the length of what's left after cutting is kind of like the waiting time, so an exponential distribution makes sense. 
normal or lognormal are also acceptable

2. A chess grandmaster's win percentage

**beta**. The beta distribution describes percentages.

3. Number of coding errors (bugs) in student homework assignments

**poisson** since coding errors are discrete
(geometric or negative binomial or even normal are also acceptable)

4. Deviation from the mean height in a classroom of toddlers

**normal**. The height of toddlers is likely normally distributed, and the distribution of deviations is the same as the mean-centered normal distribution.

5. Number of times you have to flip a USB drive over before you successfully put it into your computer

**geometric**.The geometric distribution describes how many failures you expect to have before a success.

6. Number of games before your favorite sports team wins a game

**geometric**.The geometric distribution describes how many failures you expect to have before a success. (Could also be negative binomial)

7. Human arm length

**Normal** -- similar to human height

8. Number of seagulls circling a fishing boat

any of the following: {negative binomial, poisson, geometric}. Poisson makes the most sense if you think about a discrete number of seagulls.

9. If you're 5th in line at a taxi stand, how long will you have to wait for a taxi?

**Gamma** distribution describes the distribution of waiting times for a poisson-distributed process.

### Question 2

What distribution do you think will be most useful for your future data analysis. Explain why in a few sentences. Alternatively, talk about a distribution that you are sure you will not use.

\
As a quantitative geneticist, I think I use the normal distribution for everything!
\

### Question 3

Was there anything in the distribution demos that surprised you? (This could include the fun trivia).
\
I was surprised at how so many of the distributions relate to eachother, for example that the gamma distribution is made up of exponential distributions.
