---
title: "Inference Battle Data - Death By Poisson"
author: "Sophie Ellis, Katie King, Matt Nelson, Conor O'Kane, Danny Victor"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Team Name: Death By Poisson
### Poisson, Linear, Link Function: Log 

## Simulated Data
```{r Simulate Data}
contaminantLevel <- runif(1000,0,100)
deathAlpha <- -4.56
deathBeta <- 0.071
deaths <- rpois(length(contaminantLevel),lambda=exp(deathAlpha + deathBeta*contaminantLevel))
plot(deaths~contaminantLevel, xlab = "Contaminant Level (ppm)", ylab = "Fish Mortality",
     main = "Fish Mortality in a Lake Compared to its Contaminant Level")
hist(deaths)
hist(contaminantLevel)
```

## Data Frame
```{r Data Frame}
data = data.frame("predictor" = contaminantLevel, "response" = deaths)
write.csv(data, "C:\\Users\\QFC Student\\OneDrive\\Documents\\RStatsClass\\data\\DeathByPoissonData.csv", row.names = TRUE)
```

## Biological Scenario 
Fish mortality in lakes are thought to be linked to contaminant levels in those lakes. 
The data shown compares the number of fish deaths in different lakes to its 
level of a specific contaminant ( in parts per million).