---
title: "Model Building: putting it all together"
output:
  html_document: default
  pdf_document: default
language: R
---

<!-- To render the assignment in Rmarkdown, enter the command below in the R console -->
<!-- rmarkdown::render("Class_24_Assignment.Rmd") -->

#### Due by the beginning of next class (12/3)

Save this Rmarkdown script as a file named “YourlastName_Assignment24.Rmd”. 
For each question, fill out the answer and, where requested, 
provide the relevant R code using "```" and the echo = TRUE argument.

When finished, Knit your script together into an html report, 
saved as “YourlastName_Assignment24.html” and upload the 
resulting file to the D2L site (in today’s class folder) to turn it in. 
It is due before our next class.

\

**This homework assignment will test your abilities to:**

1. think critically and creatively about model building

2. extrapolate from in-class exercises to simulate data and do inference with generalized linear models

3. hone your R skillz: function building, data visualization, etc.

\

### Question 1

Explain in your own words each of the terms in each of the equations below, 
as well as what each equation is doing, and what they are all doing together.

$Y_i \sim \mathcal{Pois}(\lambda_i=f(x_i))$ \
$\lambda = \text{exp}(f(x_i))$ \
$f(x_i) = \alpha + \beta x_i$ \


### Question 2

Write mle2 code blocks for the following models.
For each, define an R function for the inverse link function and 
the deterministic function, and write out the mle2 call 
using a data frame with named columns "predictor" and "response".

A) Binomial regression (sample size of 15)

B) Poisson Regression

C) Linear model (aka Normal regression)


### Question 3

Use mle2 to infer the parameters of the model 
I used to simulate the data saved in the "mysteryData.Robj" 
file in the Class 24 homework folder on D2L.

Plot the line from the model you fit and also 
a histogram of the residuals (the observed data - 
their expected value for all data points).



